package de.adamwest.database;

import java.util.List;
import de.adamwest.database.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EVENT.
 */
public class Event {

    private Long id;
    private String name;
    private String description;
    private Long routeId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EventDao myDao;

    private RouteLocation routeLocation;
    private Long routeLocation__resolvedKey;

    private List<MultimediaElement> multimediaElementList;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, String name, String description, Long routeId) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.routeId = routeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEventDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getRouteId() {
        return routeId;
    }

    public void setRouteId(Long routeId) {
        this.routeId = routeId;
    }

    /** To-one relationship, resolved on first access. */
    public RouteLocation getRouteLocation() {
        Long __key = this.eventId;
        if (routeLocation__resolvedKey == null || !routeLocation__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            RouteLocationDao targetDao = daoSession.getRouteLocationDao();
            RouteLocation routeLocationNew = targetDao.load(__key);
            synchronized (this) {
                routeLocation = routeLocationNew;
            	routeLocation__resolvedKey = __key;
            }
        }
        return routeLocation;
    }

    public void setRouteLocation(RouteLocation routeLocation) {
        synchronized (this) {
            this.routeLocation = routeLocation;
            eventId = routeLocation == null ? null : routeLocation.getId();
            routeLocation__resolvedKey = eventId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<MultimediaElement> getMultimediaElementList() {
        if (multimediaElementList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MultimediaElementDao targetDao = daoSession.getMultimediaElementDao();
            List<MultimediaElement> multimediaElementListNew = targetDao._queryEvent_MultimediaElementList(id);
            synchronized (this) {
                if(multimediaElementList == null) {
                    multimediaElementList = multimediaElementListNew;
                }
            }
        }
        return multimediaElementList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetMultimediaElementList() {
        multimediaElementList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
