package de.adamwest.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCATION.
 */
public class Location {

    private Long id;
    private Long Latitude;
    private Long Longitude;
    private Long Timestamp;

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, Long Latitude, Long Longitude, Long Timestamp) {
        this.id = id;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
        this.Timestamp = Timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLatitude() {
        return Latitude;
    }

    public void setLatitude(Long Latitude) {
        this.Latitude = Latitude;
    }

    public Long getLongitude() {
        return Longitude;
    }

    public void setLongitude(Long Longitude) {
        this.Longitude = Longitude;
    }

    public Long getTimestamp() {
        return Timestamp;
    }

    public void setTimestamp(Long Timestamp) {
        this.Timestamp = Timestamp;
    }

}
