package de.adamwest.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MULTIMEDIA_ELEMENT.
 */
public class MultimediaElement {

    private Long id;
    private String type;
    private String path;
    private String description;
    private java.util.Date createdAt;
    private Long eventId;

    public MultimediaElement() {
    }

    public MultimediaElement(Long id) {
        this.id = id;
    }

    public MultimediaElement(Long id, String type, String path, String description, java.util.Date createdAt, Long eventId) {
        this.id = id;
        this.type = type;
        this.path = path;
        this.description = description;
        this.createdAt = createdAt;
        this.eventId = eventId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

}
