package de.adamwest.database;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import de.adamwest.database.MultimediaElement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MULTIMEDIA_ELEMENT.
*/
public class MultimediaElementDao extends AbstractDao<MultimediaElement, Long> {

    public static final String TABLENAME = "MULTIMEDIA_ELEMENT";

    /**
     * Properties of entity MultimediaElement.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, String.class, "Type", false, "TYPE");
        public final static Property Path = new Property(2, String.class, "Path", false, "PATH");
    };

    private Query<MultimediaElement> event_MultimediaElementsQuery;

    public MultimediaElementDao(DaoConfig config) {
        super(config);
    }
    
    public MultimediaElementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MULTIMEDIA_ELEMENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TYPE' TEXT," + // 1: Type
                "'PATH' TEXT);"); // 2: Path
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MULTIMEDIA_ELEMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MultimediaElement entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Type = entity.getType();
        if (Type != null) {
            stmt.bindString(2, Type);
        }
 
        String Path = entity.getPath();
        if (Path != null) {
            stmt.bindString(3, Path);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MultimediaElement readEntity(Cursor cursor, int offset) {
        MultimediaElement entity = new MultimediaElement( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // Path
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MultimediaElement entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MultimediaElement entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MultimediaElement entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "MultimediaElements" to-many relationship of Event. */
    public List<MultimediaElement> _queryEvent_MultimediaElements(Long id) {
        synchronized (this) {
            if (event_MultimediaElementsQuery == null) {
                QueryBuilder<MultimediaElement> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id.eq(null));
                event_MultimediaElementsQuery = queryBuilder.build();
            }
        }
        Query<MultimediaElement> query = event_MultimediaElementsQuery.forCurrentThread();
        query.setParameter(0, id);
        return query.list();
    }

}
